### ISSUE TITLE
[BUG] demo is not work

### ISSUE THREAD

**Issue by suc8899** [reactiveui/ReactiveUI.Samples#531]
**Describe the bug**
ReactiveUI.Samples-main\winforms\demo2\WinForms.Reactive.Client
this demo is not work,no data 
**Steps To Reproduce**
1. git clone `https://github.com/reactiveui/ReactiveUI.Samples`
2.go to dir  `ReactiveUI.Samples-main\winforms\demo2\WinForms.Reactive.Client`
3.click WinForms.Reactive.Client.csproj to open 
4.run app

**Expected behavior**
work well

**Screenshots**
![q](https://user-images.githubusercontent.com/101682277/158501783-46e4ffda-a976-4661-8cd8-9745ae19091c.gif)

**Environment**
- OS:      windows 10
- Device:   dell notebook
- Version:   19041.450
- Working Version: 19041.450

**Comment by glennawatson** [comment]
Thanks for the issue. Please edit to bring back the full issue template otherwise gotta close this one.

**Comment by glennawatson** [comment]
See https://github.com/reactiveui/ReactiveUI.Samples/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+Summary+of+item for an example

**Comment by suc8899** [comment]
@glennawatson  issues have been fixed

**Comment by glennawatson** [comment]
Thankyou, I'll have a look later in the week. This sample was only recently added.

**Comment by rallets** [comment]
Hi @suc8899 can you try to remove
`initialValue: Enumerable.Empty<ItemDto>()`
From ItemsViewModel.cs, line 88 ?

**Comment by suc8899** [comment]
@rallets  I have tried it, the problem is still not solved

**Comment by rallets** [comment]
@glennawatson not sure why, but now the code that was working, it throws an exception. It's related to the property being an IEnumerable, but the ListBox DataBinding is expecting a IList or IListSource. All the packages are up to date. I have a fix that consists in replacing IEnumerable to IList, but I'm wondering if you have any tips on what this can be related to, or if it's a smell of another problem.
I have sent a [PR #542](https://github.com/reactiveui/ReactiveUI.Samples/pull/532) that fixes the problem. @suc8899 if you want you can try that branch.

The exception is:
```
PropertyBinderImplementation: view.lstDetails.DataSource Binding received an Exception! - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Complex DataBinding accepts as a data source either an IList or an IListSource. (Parameter 'value')
   at System.Windows.Forms.ListControl.set_DataSource(Object value)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass11_0`3.<BindToDirect>g__SetThenGet|0(Object paramTarget, Object paramValue, Object[] paramParams) in /_/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:line 296
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass11_0`3.<BindToDirect>b__7(<>f__AnonymousType0`2 x) in /_/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs:line 318
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 39
```

**Comment by glennawatson** [comment]
Possibly an update with .NET 6? Seems to be a hard requirement by winforms anyway.

Thanks for your fix, @suc8899 if you can confirm if that merge fixes it for you?

**Comment by suc8899** [comment]
It's work ok,IEnumerable change to IList,thank you @rallets  @glennawatson

**Comment by glennawatson** [comment]
Thanks @suc8899  closing the issue now
